name: testEndToEnd
on:
  push:
  pull_request:
    types: [opened, reopened]
  schedule:
    - cron: "44 4 * * *"

jobs:
  testEverything:
    strategy:
      matrix:
        #python_version: [3.9.16, 3.10.10, 3.11.2]
        #operating_system: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12]
        python_version: ["3.10"]
        operating_system: ["ubuntu-latest"]
    runs-on: ${{ matrix.operating_system }}
    steps:
      #Checkout the current branch
      - name: Checkout repo
        uses: actions/checkout@v3

      #Install the given version of Python we will test against
      - name: Install Required Python Version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          architecture: "x64"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install contentctl and activate the shell
        run: |
          poetry install --no-interaction
          # echo "DONE"
          # poetry --help
          # poetry install --no-interaction
          # echo "ABOUT TO DO AN INSTALL"
          # ls -lah
          # poetry install --no-interaction --no-root -vvv
          # echo "WOW, DONE WITH INSTALL"

      - name: Make a new directory, cd into it, and initialize a new content pack
        run: |
          mkdir my_demo_app
          cd my_demo_app
          poetry run contentctl init

      - name: Run contentctl validate
        run: |
          poetry run contentctl validate

      - name: Run contentctl build
        run: |
          poetry run contentctl build

      #Do not pause on a failed detection
      - name: Run contentctl test
        run: |
          poetry run contentctl test --behavior never_pause
