name: nightly-build
on:
  push:

jobs:
  nightly:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout security_content_docs
        uses: actions/checkout@v3

      - name: install python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: install dependencies
        run: poetry install --no-interaction
